### ISSUE TITLE
Plug-in this control is being held down after quick-hopping worlds

### ISSUE THREAD

**Issue by nmehta94** [geheur/More-menu-entry-swaps#12] opened 2022-07-12 12:28 UTC
I have control set to "USE" for items in my inventory. When I quick hop worlds using shift+control+arrow keys, after swapping worlds, RuneLite thinks my control key is still being held down (all my items in my inventory are set to USE). I need to press control again to revert my inventory options to normal.

![image](https://user-images.githubusercontent.com/8924734/178489703-73fbb16e-e170-4a52-8e4c-1d821521304b.png)

**Comment by geheur** [comment] 2022-07-13 02:50
sounds like a duplicate of #8.

**Closed by geheur** 2022-07-13 02:50 UTC
